### ISSUE TITLE
more size variants

### ISSUE THREAD

**Issue by deathtrip** [varlesh/volantes-cursors#1]
First off, great cursor! 
Could you add a 24 size version, and also some bigger ones for hidpi screens.

**Comment by varlesh** [comment]
24px size will be blurred with bad quality, because initial size have 32px. For HiDPI already available 64px.

**Comment by deathtrip** [comment]
You only get blurring if you upscale an image to higher resolution, so downsizing it should be fine.

**Comment by areographe** [comment]
Hey, it would be great if a 22 or 24 px version was available

**Comment by logrusorgru** [comment]
> You only get blurring if you upscale an image to higher resolution, so downsizing it should be fine.

Both, upscale and downscale are about image interpolation. Just add a desired size here https://github.com/varlesh/volantes-cursors/blob/master/build.sh#L22 and check out how the Inkscape performs the interpolation.

**Comment by jokerekv2** [comment]
For me it's just too big...
