### ISSUE TITLE
Tiny cursor on 4k screen

### ISSUE THREAD

**Issue by Rend0e** [varlesh/volantes-cursors#5]
Hi, my laptop display is 4k whereas my monitor is 1080p, the cursor is fine on 1080p, however on the laptop 4k screen it's too tiny so perhaps a scaling issue?

**Comment by varlesh** [comment]
Cursors have 4 sizes: 24px, 32px, 48px and 64px. For example, Breeze cursors have sizes 24px, 36px and 48px

**Comment by Rend0e** [comment]
Is there a way to make the scale consistent? It looks fine at 1080p on the 4k laptop screen but at native 4k it is way too small. Default gnome cursor scales properly.

**Comment by varlesh** [comment]
Try change cursor size on:
`gsettings set org.gnome.desktop.interface cursor-size 64`

**Comment by Rend0e** [comment]
Thanks, `gsettings set org.gnome.desktop.interface cursor-size 48`, did the trick! Cursor looks great!
